In [38]:
import pandas as pd

In [177]:
df = pd.read_csv('./recipe.csv', encoding='cp949', encoding_errors='ignore')
df.head()

,RCP_SNO,RCP_TTL,CKG_NM,RGTR_ID,RGTR_NM,INQ_CNT,RCMM_CNT,SRAP_CNT,CKG_MTH_ACTO_NM,CKG_STA_ACTO_NM,CKG_MTRL_ACTO_NM,CKG_KND_ACTO_NM,CKG_IPDC,CKG_MTRL_CN,CKG_INBUN_NM,CKG_DODF_NM,CKG_TIME_NM,FIRST_REG_DT
0,128671,어묵김말이,어묵김말이,skfo0701,꽃날,10072,6,66,튀김,간식,가공식품류,디저트,맛있는 김말이에 쫄깃함을 더한 어묵 김말이예요-,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,2인분,초급,60분이내,20070402131403
1,128892,두부에 꼬리가 달렸어요!!,두부새우전,skfo0701,꽃날,5817,3,27,부침,일상,해물류,밑반찬,꼬리가 너-무- 매력적인 두부새우전. 두부와 야채를 한번에!! 영양까지 만점인 두부...,[재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...,3인분,초급,30분이내,20070402205937
2,128932,입안에서 톡톡톡,알밥,skfo0701,꽃날,6975,8,36,굽기,일상,해물류,밥/죽/떡,간단하게 만들어 보는 알이 톡톡톡 알밥♥ 다 먹고 누룽지까지 싹싹 긁어먹는게 최고죠...,[재료] 밥 1+1/2공기| 당근 1/4개| 치자단무지 1/2개| 신김치 1쪽| 무...,2인분,초급,30분이내,20070402224355
3,131871,★현미호두죽,현미호두죽,cds1117,햇님&별님,3339,0,11,끓이기,일상,쌀,밥/죽/떡,현미호두죽,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,2인분,초급,30분이내,20070410142301
4,139247,부들부들 보들보들 북어갈비♥,북어갈비,skfo0701,꽃날,7173,3,97,굽기,술안주,건어물류,메인반찬,오늘은 집에서 굴러다니고 쉽게 구할 수 있는 북어로 일품요리를 만들어 보았어요! 도...,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,2인분,초급,60분이내,20070501000844

In [178]:
len(df['CKG_NM'].unique())

49680

In [179]:
df = df.drop_duplicates(subset='CKG_NM', keep='first')
len(df)

49680

In [181]:
import requests, json
from bs4 import BeautifulSoup

def food_info(name):
    '''
    This function gives you food information for the given input.

    PARAMETERS
        - name(str): name of Korean food in Korean ex) food_info("김치찌개")
    RETURN
        - res(dict): dict containing info for some Korean food related to 'name'
            - res['name'](str): name of food
            - res['ingredients'](str): ingredients to make the food
            - res['recipe'](list[str]): contain recipe in order
    '''
    url = f"https://www.10000recipe.com/recipe/list.html?q={name}"
    response = requests.get(url)
    if response.status_code == 200:
        html = response.text
        soup = BeautifulSoup(html, 'html.parser')
    else: 
        print("HTTP response error :", response.status_code)
        return
    
    food_list = soup.find_all(attrs={'class':'common_sp_link'})
    if not food_list:
        print(f"No results found for {name}")
        return
    
    food_id = food_list[0]['href'].split('/')[-1]
    new_url = f'https://www.10000recipe.com/recipe/{food_id}'
    new_response = requests.get(new_url)
    if new_response.status_code == 200:
        html = new_response.text
        soup = BeautifulSoup(html, 'html.parser')
    else: 
        print("HTTP response error :", new_response.status_code)
        return
    
    food_info = soup.find(attrs={'type':'application/ld+json'})
    
    if food_info is None:
        print(f"No structured data found for {name}")
        return
    
    try:
        result = json.loads(food_info.text)
    except json.JSONDecodeError as e:
        print(f"JSON parsing error: {e}")
        return

    # 'recipeIngredient'와 'recipeInstructions'가 있는지 확인
    ingredient_list = result.get('recipeIngredient', None)
    if ingredient_list:
        ingredients = ', '.join(ingredient_list)
    else:
        ingredients = 'No ingredients available'
    
    recipe_list = result.get('recipeInstructions', None)
    if recipe_list:
        recipe = [step.get('text', 'No instructions available') for step in recipe_list]
        recipe = [f'{i+1}. {step}' for i, step in enumerate(recipe)]
    else:
        recipe = ['No recipe available']
    
    res = {
        'name': name,
        'ingredients': ingredients,
        'recipe': recipe
    }
    
    return res

In [182]:
results = []
# CKG_NM 열의 값들을 하나씩 반복하여 food_info 호출
for food_name in df['CKG_NM'].head(10):
    food_data = food_info(food_name)
    if food_data:  # food_info가 None이 아닌 경우에만 추가
        results.append(food_data)

result_df = pd.DataFrame(results)

In [183]:
result_df.head()

,name,ingredients,recipe
0,어묵김말이,No ingredients available,[No recipe available]
1,두부새우전,"손두부 1모, 새우 20g, 부추 10g, 달걀 1개, 소금 약간, 부침유 적당히,...",[1. 두부는 먹기 좋은 크기로 직사각형으로 1Cm정도을 두께로 썰어 소금으로 밑간...
2,알밥,"쌀밥 2공기, 날치알 2큰술, 맛살 2줄, 다진단무지 4큰술, 어린잎채소 2줌, 도...","[1. '날치알' 하나면 영양&비주얼 동시 캐치!, 2. 단무지, 맛살을 잘게 다져..."
3,현미호두죽,"현미 4컵, 찹쌀 2컵, 호두 50g, 물 1/2컵, 소금 약간","[1. 현미와 찹쌀은 씻어서 불린 후 분말기로 적당히 간다., 2. 호두는 끓는 물..."
4,북어갈비,"북어포 1마리, 찹쌀가루 1C, 간장 2T, 설탕 1T, 물 1T, 다진파 1T, ...",[1. 북어포를 준비해주세여.머리랑 꼬리는 잘라주시고 지느러미도 정리해주세요.그리고...

### recipe   
[] , \n, 'No recipe available' 삭제

In [ ]:
result_df['recipe'] = result_df['recipe'].apply(lambda x: '\n'.join(x).replace('[','').replace(']',''))

In [185]:
def clean_recipe(recipe_str):
    # 숫자와 점(예: '1.', '2.')을 제거하고, 줄바꿈 문자를 모두 제거하는 정규 표현식
    cleaned = recipe_str.replace('\n', ' ') # 줄바꿈 문자를 공백으로 대체
    return cleaned

In [186]:
result_df['recipe'] = result_df['recipe'].apply(clean_recipe)

In [188]:
result_df = result_df[~result_df['recipe'].apply(lambda x: 'No recipe available' in x)].reset_index(drop=True)

### ingredients

In [190]:
import re
def clean_ingredients(ingredient_str):
    # 숫자+한글, 숫자+영어, "1/2개" 등 제거하는 정규 표현식
    cleaned = re.sub(r'\d+/\d+[가-힣]*|\d+[a-zA-Z가-힣]*|약간|적당히', '', ingredient_str)
    # 쉼표로 나누고 공백 제거
    cleaned_list = [item.strip() for item in cleaned.split(',') if item.strip()]
    return ', '.join(cleaned_list)

In [191]:
result_df['ingredients'] = result_df['ingredients'].apply(clean_ingredients)

In [192]:
result_df.head()

,name,ingredients,recipe
0,두부새우전,"손두부, 새우, 부추, 달걀, 소금, 부침유, 참기름",1. 두부는 먹기 좋은 크기로 직사각형으로 1Cm정도을 두께로 썰어 소금으로 밑간해...
1,알밥,"쌀밥, 날치알, 맛살, 다진단무지, 어린잎채소, 도시락 김, 참기름, 통깨, 다진김...","1. '날치알' 하나면 영양&비주얼 동시 캐치! 2. 단무지, 맛살을 잘게 다져주세..."
2,현미호두죽,"현미, 찹쌀, 호두, 물, 소금",1. 현미와 찹쌀은 씻어서 불린 후 분말기로 적당히 간다. 2. 호두는 끓는 물에 ...
3,북어갈비,"북어포, 찹쌀가루, 간장, 설탕, 물, 다진파, 다진마늘, 참기름, 깨소금, 후춧가루",1. 북어포를 준비해주세여.머리랑 꼬리는 잘라주시고 지느러미도 정리해주세요.그리고 ...
4,토마토스파게티,"스파게티 면, 해물 믹스, 양파, 청양고추, 베이컨, 물, 통후추 적당량, 시판 토...","1. 양파는 채 썰고 청양고추 1개는 총총 썰고, 베이컨은 먹기 좋게 썰어줍니다. ..."

In [194]:
result_df['recipe'][0]

'1. 두부는 먹기 좋은 크기로 직사각형으로 1Cm정도을 두께로 썰어 소금으로 밑간해 주고 부추는 쫑쫑 잘게 썰고 달걀은 잘 풀어 주세요~ 새우는 잘 씻어 물기를 빼고 준비해 주세요~ 2. 두부는 키친타올로 물기를 닦은후 팬에 기름을 두르고 팬에 올려 주세요~ 3. 앞면이 익으면 뒤도 뒤집어 가며 노릇하게 부쳐 주세요~ 4. 노릇하게 부쳐진 두부위에 새우를 한마리씩 올려 주세요~ 5. 풀어둔 달걀물을 숟가락으로 새우위에 조금씩 올려 주세요~ 그래야 새우가 잘 붙는 답니다 6. 쫑쫑 썰어 둔 부추를 새우 위 아래 부분에 올린후 달걀물을 숟가락으로 떠서 잘 붙도록 해 준 후 뒤집어 한번 살짝 더 익혀 주면 완성되요~'