In [33]:
import numpy as np
import pandas as pd

In [34]:
df = pd.read_csv('D:/김동영/12_Gitub/mygit/mygit/비즈니스시계열/Data/미세먼지_PM10__월별_도시별_대기오염도_20250511223309.csv', encoding='cp949')

In [35]:
df.head()

,구분(1),구분(2),2018.01,2018.02,2018.03,2018.04,2018.05,2018.06,2018.07,2018.08,...,2024.01,2024.02,2024.03,2024.04,2024.05,2024.06,2024.07,2024.08,2024.09,2024.1
0,총계,소계,50,52,49,56,43,38,28,24,...,33,29,45,50,30,29,19,22,18,23
1,서울특별시,서울특별시,52,53,52,52,42,37,24,22,...,36,33,49,50,30,31,20,24,16,23
2,부산광역시,부산광역시,45,52,44,63,44,41,37,28,...,27,22,38,54,27,26,15,19,15,17
3,대구광역시,대구광역시,47,48,43,56,40,36,27,22,...,34,26,41,53,29,27,16,17,16,20
4,인천광역시,인천광역시,48,49,49,46,40,34,26,25,...,38,35,51,51,31,30,23,27,18,28

In [36]:
df = df.iloc[[0]]
df

,구분(1),구분(2),2018.01,2018.02,2018.03,2018.04,2018.05,2018.06,2018.07,2018.08,...,2024.01,2024.02,2024.03,2024.04,2024.05,2024.06,2024.07,2024.08,2024.09,2024.1
0,총계,소계,50,52,49,56,43,38,28,24,...,33,29,45,50,30,29,19,22,18,23

In [37]:
df = df.drop(columns=['구분(2)'])
df

,구분(1),2018.01,2018.02,2018.03,2018.04,2018.05,2018.06,2018.07,2018.08,2018.09,...,2024.01,2024.02,2024.03,2024.04,2024.05,2024.06,2024.07,2024.08,2024.09,2024.1
0,총계,50,52,49,56,43,38,28,24,24,...,33,29,45,50,30,29,19,22,18,23

In [38]:
df_pivot = pd.melt(df, id_vars=['구분(1)'], var_name='Date', value_name='Value')
df_pivot

   구분(1)     Date Value
0     총계  2018.01    50
1     총계  2018.02    52
2     총계  2018.03    49
3     총계  2018.04    56
4     총계  2018.05    43
..   ...      ...   ...
77    총계  2024.06    29
78    총계  2024.07    19
79    총계  2024.08    22
80    총계  2024.09    18
81    총계   2024.1    23

[82 rows x 3 columns]

In [39]:
df_pivot = df_pivot.drop(columns=['구분(1)'])
df_pivot

       Date Value
0   2018.01    50
1   2018.02    52
2   2018.03    49
3   2018.04    56
4   2018.05    43
..      ...   ...
77  2024.06    29
78  2024.07    19
79  2024.08    22
80  2024.09    18
81   2024.1    23

[82 rows x 2 columns]

In [40]:
df_pivot = df_pivot.rename(columns={'Value': '미세먼지'})
df_pivot

       Date 미세먼지
0   2018.01   50
1   2018.02   52
2   2018.03   49
3   2018.04   56
4   2018.05   43
..      ...  ...
77  2024.06   29
78  2024.07   19
79  2024.08   22
80  2024.09   18
81   2024.1   23

[82 rows x 2 columns]

In [53]:
rain = pd.read_csv('D:/김동영/12_Gitub/mygit/mygit/비즈니스시계열/Data/평균강수량2.csv', encoding='cp949')

In [54]:
rain.head()

           년월  평균 강수량(mm)
0  2018-01-01     27.0750
1  2018-02-01     40.9500
2  2018-03-01    114.0750
3  2018-04-01    125.2125
4  2018-05-01    131.0750