In [3]:
import os
import sys
import urllib.request
import pandas as pd
import json
import re

## 네이버 웹문서 검색 API

In [21]:
client_id = "tc_Qk1GpVYMPIAbmsekz"
client_secret = "oi5UIeflM7"

query = urllib.parse.quote(input("검색 질의: "))
idx = 0
display = 100
start = 1
end = 1000

web_df = pd.DataFrame(columns=("Title", "Link", "Description"))

for start_index in range(start, end, display):
  url = "https://openapi.naver.com/v1/search/webkr?query=" + query \
    + "&display=" + str(display) \
    + "&start=" + str(start_index)

  request = urllib.request.Request(url)
  request.add_header("X-Naver-Client-Id",client_id)
  request.add_header("X-Naver-Client-Secret",client_secret)
  response = urllib.request.urlopen(request)
  rescode = response.getcode()
  if(rescode==200):
      response_body = response.read()
      response_dict = json.loads(response_body.decode('utf-8'))
      items = response_dict['items']
      for item_index in range(0, len(items)):
        remove_tag = re.compile('<.*?>')
        title = re.sub(remove_tag, '', items[item_index]['title'])
        link = items[item_index]['link']
        description = re.sub(remove_tag, '', items[item_index]['description'])
        web_df.loc[idx] = [title, link, description]
        idx += 1
  else:
      print("Error Code:" + rescode)
  
  
  web_df

In [22]:
web_df

,Title,Link,Description
0,상장지수펀드 - 나무위키,https://namu.wiki/w/%EC%83%81%EC%9E%A5%EC%A7%8...,상장 지수 펀드 / Exchange Traded Fund(ETF) / 上場指數 상장...
1,ETF : 네이버페이 증권,https://finance.naver.com/sise/etf.nhn,"ETF(상장지수펀드)는 기초지수의 성과를 추적하는 것이 목표인 인덱스펀드로, 거래소..."
2,ETF의 정의 | ETF의 이해 | ETF 알기 | 미래에셋 TIGER ETF,http://www.tigeretf.com/ko/education/etf_justi...,ETF는 거래소에 상장되어 있기 때문에 일반주식과 같은 방법으로 거래를 하실 수 있...
3,ETF - 대한민국 대표 기업공시채널 KIND,https://kind.krx.co.kr/disclosure/disclosureby...,"시간: 2024-10-04 11:09, 종목명: SOL 미국배당다우존스TR, 공시제..."
4,ETF - 시사경제용어사전,https://terms.naver.com/entry.naver?docId=5143...,ETF(Exchange Traded Fund)는 말 그대로 인덱스펀드를 거래소에 상...
...,...,...,...
195,TCW Transform Supply Chain ETF (SUPP) Chart an...,https://www.marketbeat.com/stocks/NYSEARCA/SUP...,View TCW Transform Supply Chain ETF (NYSEARCA:...
196,IQ Cleaner Transport ETF (CLNR) Dividend Yield...,https://www.marketbeat.com/stocks/NYSEARCA/CLN...,Is IQ Cleaner Transport ETF (NYSEARCA:CLNR) a ...
197,Invesco Global Clean Energy ETF (PBD) Dividend...,https://www.marketbeat.com/stocks/NYSEARCA/PBD...,Is Invesco Global Clean Energy ETF (NYSEARCA:P...
198,American Century Sustainable Growth ETF (ESGY)...,https://www.marketbeat.com/stocks/NYSEARCA/ESG...,Which shareholders are buying/selling shares o...
199,American Conservative Values ETF (ACVF) Chart ...,https://www.marketbeat.com/stocks/NYSEARCA/ACV...,View American Conservative Values ETF (NYSEARC...

In [32]:
query = urllib.parse.quote(input("검색 질의: "))
idx = 0
display = 100
start = 1
end = 1000

web_df2 = pd.DataFrame(columns=("Title", "Link", "Description"))

for start_index in range(start, end, display):
  url = "https://openapi.naver.com/v1/search/webkr?query=" + query \
    + "&display=" + str(display) \
    + "&start=" + str(start_index)

  request = urllib.request.Request(url)
  request.add_header("X-Naver-Client-Id",client_id)
  request.add_header("X-Naver-Client-Secret",client_secret)
  response = urllib.request.urlopen(request)
  rescode = response.getcode()
  if(rescode==200):
      response_body = response.read()
      response_dict = json.loads(response_body.decode('utf-8'))
      items = response_dict['items']
      for item_index in range(0, len(items)):
        remove_tag = re.compile('<.*?>')
        title = re.sub(remove_tag, '', items[item_index]['title'])
        link = items[item_index]['link']
        description = re.sub(remove_tag, '', items[item_index]['description'])
        web_df2.loc[idx] = [title, link, description]
        idx += 1
  else:
      print("Error Code:" + rescode)
  
  
  web_df2

In [33]:
web_df2

,Title,Link,Description
0,상장지수펀드 - 나무위키,https://namu.wiki/w/%EC%83%81%EC%9E%A5%EC%A7%8...,상장 지수 펀드 / Exchange Traded Fund(ETF) / 上場指數 상장...
1,상장지수펀드 - 대학생을 위한 실용 금융,https://terms.naver.com/entry.naver?docId=3431...,흔히 ETF라고 불리는 상장지수펀드는 특정한 지수의 움직임에 연동해서 운용되는 인덱...
2,ETF - 시사경제용어사전,https://terms.naver.com/entry.naver?docId=5143...,ETF(Exchange Traded Fund)는 말 그대로 인덱스펀드를 거래소에 상...
3,ETF 소개 | ETF 투자기초가이드 | Kodex,https://m.samsungfund.com/etf/insight/guide/vi...,"상장 지수 펀드, ETF ; ETF란 Exchage Traded Fund의 줄임말로..."
4,"ETF란? 뜻, 단점, 장점, 투자 방법 총정리! | 뱅크샐러드",https://www.banksalad.com/articles/ETF-%EB%9C%...,"어렵게만 느껴지는 ETF가 무엇인지, 이해하기 쉽게 알려드릴게요."
...,...,...,...
145,선생님...대체 ETF가 뭡니까? | 사이다경제,https://cidermics.com/contents/detail/2162,에디터의 다른글 ; &quot;평범한 사람은 모른다&quot; 상류층 되려면 무조건...
146,ETF찾기 | Kodex,https://m.samsungfund.com/etf/product/list.do,Kodex ETF 상품별 가격과 수익률을 확인해보세요.
147,ETF - 타임폴리오자산운용,https://www.timefolio.co.kr/etf/funds_list.php,TIMEFOLIO 글로벌우주테크&amp;방산액티브 ETF (478150) ; To ...
148,PLUS ETF | 한화자산운용,https://www.plusetf.co.kr/,PLUS ETF는 글로벌 전문가들의 안목으로 보지 못한 새로운 투자 기회를 발견하고...
149,ETF 분배금 조회,https://search-etf.com/,"4년간의 연도별/분기별 ETF 분배금 조회, 배당 검색"

## 네이버 뉴스 API

In [23]:
query = urllib.parse.quote(input("검색 질의: "))
idx = 0
display = 100
start = 1
end = 1000
sort = "sim"

news_df = pd.DataFrame(columns=("Title", "Link", "Description", "PubDate"))

for start_index in range(start, end, display):
  url = "https://openapi.naver.com/v1/search/news?query=" + query \
    + "&display=" + str(display) \
    + "&start=" + str(start_index) \
    + "&sort=" + sort 

  request = urllib.request.Request(url)
  request.add_header("X-Naver-Client-Id",client_id)
  request.add_header("X-Naver-Client-Secret",client_secret)
  response = urllib.request.urlopen(request)
  rescode = response.getcode()
  if(rescode==200):
      response_body = response.read()
      response_dict = json.loads(response_body.decode('utf-8'))
      items = response_dict['items']
      for item_index in range(0, len(items)):
        remove_tag = re.compile('<.*?>')
        title = re.sub(remove_tag, '', items[item_index]['title'])
        link = items[item_index]['link']
        description = re.sub(remove_tag, '', items[item_index]['description'])
        pubDate = items[item_index]['pubDate']
        news_df.loc[idx] = [title, link, description, pubDate]
        idx += 1
  else:
      print("Error Code:" + rescode)
  
  
  news_df

In [24]:
news_df

,Title,Link,Description,PubDate
0,"키움증권, 중개형 ISA계좌서 ETF거래시 '최대 14만원' 혜택",https://n.news.naver.com/mnews/article/003/001...,키움증권은 중개형 ISA계좌에서 상장지수펀드(ETF)를 거래하면 최대 14만원의 혜...,"Fri, 04 Oct 2024 11:10:00 +0900"
1,"하나자산운용, 현대차그룹 채권 ETF 상장",https://n.news.naver.com/mnews/article/117/000...,하나자산운용이 ETF 시장에 새로운 바람을 불어넣는다. 하나자산운용은 현대차그룹 계...,"Fri, 04 Oct 2024 17:32:00 +0900"
2,"하나운용, 현대차그룹 채권 ETF 상장… “대기업 집중투자”",https://n.news.naver.com/mnews/article/366/000...,상장지수펀드(ETF)를 이달 2일 유가증권시장에 상장했다고 4일 밝혔다. ‘하나 1...,"Fri, 04 Oct 2024 10:08:00 +0900"
3,"대기업 그룹 채권에 집중 투자…하나운용, 국내 최초 채권형 ETF 출시",https://n.news.naver.com/mnews/article/243/000...,(A+이상)&amp;국고통안' ETF(상장지수펀드)를 2일 유가증권시장에 상장했다고...,"Fri, 04 Oct 2024 15:47:00 +0900"
4,키움자산운용 ETF 4종목 내달 자진 상장폐지,https://n.news.naver.com/mnews/article/001/001...,한국거래소는 신탁 원본액이 감소한 소규모 상장 상장지수펀드(ETF) 4개 종목을 운...,"Fri, 04 Oct 2024 16:34:00 +0900"
...,...,...,...,...
995,금투업계 '국감 소환' 예의주시…밸류업·금투세 쟁점,https://www.news2day.co.kr/article/20241002500029,"정무위 국감 코앞, 증인·참고인 채택기준 긴장감 증권업, 다우키움그룹 전 김익래 회...","Wed, 02 Oct 2024 08:30:00 +0900"
996,"미국증시 마감직전...반도체ETF·엔비디아·인텔 '급락', 양대 악재는?",http://www.choicenews.co.kr/news/articleView.h...,뉴욕증권거래소따르면 이 시각 뉴욕증시 반도체 관련주 흐름을 반영하는 VANECK S...,"Wed, 02 Oct 2024 05:14:00 +0900"
997,"한국투자신탁운용, 이머징마켓 가이드북 발간",https://www.econovill.com/news/articleView.htm...,배 사장은 &quot;ACE ETF는 현재의 글로벌 공급망 재편 속에서 인도를 중심...,"Fri, 27 Sep 2024 09:40:00 +0900"
998,"한국투자증권, 퇴직연금 운용사 ETF 순매수 이벤트",https://www.etoday.co.kr/news/view/2401787,상장지수펀드(ETF) 순매수 이벤트를 진행한다고 19일 밝혔다. 이번 이벤트는 개인...,"Thu, 19 Sep 2024 09:54:00 +0900"
999,"한투운용, 베트남·인도·인니·멕시코 투자 가이드북 발간",https://www.dnews.co.kr/uhtml/view.jsp?idxno=2...,ACE ETF 국내 유일 4개국 투자 라인업 보유 한국투자신탁운용은 오는 30일 ‘...,"Fri, 27 Sep 2024 11:22:00 +0900"

## 네이버 백과사전 API

In [25]:
query = urllib.parse.quote(input("검색 질의: "))
idx = 0
display = 10
start = 1
end = 100

encyc_df = pd.DataFrame(columns=("Title", "Link", "Description"))

for start_index in range(start, end, display):
  url = "https://openapi.naver.com/v1/search/encyc?query=" + query \
    + "&display=" + str(display) \
    + "&start=" + str(start_index)

  request = urllib.request.Request(url)
  request.add_header("X-Naver-Client-Id",client_id)
  request.add_header("X-Naver-Client-Secret",client_secret)
  response = urllib.request.urlopen(request)
  rescode = response.getcode()
  if(rescode==200):
      response_body = response.read()
      response_dict = json.loads(response_body.decode('utf-8'))
      items = response_dict['items']
      for item_index in range(0, len(items)):
        remove_tag = re.compile('<.*?>')
        title = re.sub(remove_tag, '', items[item_index]['title'])
        link = items[item_index]['link']
        description = re.sub(remove_tag, '', items[item_index]['description'])
        encyc_df.loc[idx] = [title, link, description]
        idx += 1
  else:
      print("Error Code:" + rescode)
  
  
encyc_df

,Title,Link,Description
0,ETF,https://terms.naver.com/entry.naver?docId=5143...,ETF(Exchange Traded Fund)는 말 그대로 인덱스펀드를 거래소에 ...
1,변화된 금융환경에서 꼭 알아야 할 투자상품,https://terms.naver.com/entry.naver?docId=1637...,"[ELS(Equity Linked Securities, 주가연계증권)] 변동성을 활..."
2,ETF,https://terms.naver.com/entry.naver?docId=1840...,인덱스 펀드와 뮤추얼 펀드의 특성을 결합한 상품이다. 2002년 처음으로 도입된 E...
3,ETF,https://terms.naver.com/entry.naver?docId=6727...,ETF(Exchange Traded Fund)는 말 그대로 인덱스펀드를 거래소에 상...
4,상장지수펀드,https://terms.naver.com/entry.naver?docId=3431...,흔히 ETF라고 불리는 상장지수펀드는 특정한 지수의 움직임에 연동해서 운용되는 인덱...
...,...,...,...
95,MSCI ESG등급,https://terms.naver.com/entry.naver?docId=6731...,세계 1700여 개 기관투자가가 이 지표를 활용해 ESG 투자를 결정하고 있으며 E...
96,금융산업의 국제화 시기,https://terms.naver.com/entry.naver?docId=2814...,"||| 거래소, 상장지수펀드(ETF) 시장 개설. | || 2003. 8. ||| ..."
97,워크자본주의,https://terms.naver.com/entry.naver?docId=6627...,정치적 올바름에 대해 적극적으로 목소리를 내는 기업들의 경영 방식을 꼬집는 용어다....
98,커버드 콜 전략,https://terms.naver.com/entry.naver?docId=5661...,커버드콜 ETF는 시장이 횡보할 때 콜옵션 매도 프리미엄으로 수익을 얻는다. 시장이...
99,뱅가드그룹,https://terms.naver.com/entry.naver?docId=2066...,3%로 액티브펀드(10.0%)를 앞질렀다. 2014년말 현재 뱅가드는 2조달러의 지...

In [27]:
combined_df = pd.concat([web_df, encyc_df], ignore_index=True)
combined_df

,Title,Link,Description
0,상장지수펀드 - 나무위키,https://namu.wiki/w/%EC%83%81%EC%9E%A5%EC%A7%8...,상장 지수 펀드 / Exchange Traded Fund(ETF) / 上場指數 상장...
1,ETF : 네이버페이 증권,https://finance.naver.com/sise/etf.nhn,"ETF(상장지수펀드)는 기초지수의 성과를 추적하는 것이 목표인 인덱스펀드로, 거래소..."
2,ETF의 정의 | ETF의 이해 | ETF 알기 | 미래에셋 TIGER ETF,http://www.tigeretf.com/ko/education/etf_justi...,ETF는 거래소에 상장되어 있기 때문에 일반주식과 같은 방법으로 거래를 하실 수 있...
3,ETF - 대한민국 대표 기업공시채널 KIND,https://kind.krx.co.kr/disclosure/disclosureby...,"시간: 2024-10-04 11:09, 종목명: SOL 미국배당다우존스TR, 공시제..."
4,ETF - 시사경제용어사전,https://terms.naver.com/entry.naver?docId=5143...,ETF(Exchange Traded Fund)는 말 그대로 인덱스펀드를 거래소에 상...
...,...,...,...
295,MSCI ESG등급,https://terms.naver.com/entry.naver?docId=6731...,세계 1700여 개 기관투자가가 이 지표를 활용해 ESG 투자를 결정하고 있으며 E...
296,금융산업의 국제화 시기,https://terms.naver.com/entry.naver?docId=2814...,"||| 거래소, 상장지수펀드(ETF) 시장 개설. | || 2003. 8. ||| ..."
297,워크자본주의,https://terms.naver.com/entry.naver?docId=6627...,정치적 올바름에 대해 적극적으로 목소리를 내는 기업들의 경영 방식을 꼬집는 용어다....
298,커버드 콜 전략,https://terms.naver.com/entry.naver?docId=5661...,커버드콜 ETF는 시장이 횡보할 때 콜옵션 매도 프리미엄으로 수익을 얻는다. 시장이...
299,뱅가드그룹,https://terms.naver.com/entry.naver?docId=2066...,3%로 액티브펀드(10.0%)를 앞질렀다. 2014년말 현재 뱅가드는 2조달러의 지...

In [28]:
news_df = news_df.drop(columns='PubDate')

In [29]:
news_df

,Title,Link,Description
0,"키움증권, 중개형 ISA계좌서 ETF거래시 '최대 14만원' 혜택",https://n.news.naver.com/mnews/article/003/001...,키움증권은 중개형 ISA계좌에서 상장지수펀드(ETF)를 거래하면 최대 14만원의 혜...
1,"하나자산운용, 현대차그룹 채권 ETF 상장",https://n.news.naver.com/mnews/article/117/000...,하나자산운용이 ETF 시장에 새로운 바람을 불어넣는다. 하나자산운용은 현대차그룹 계...
2,"하나운용, 현대차그룹 채권 ETF 상장… “대기업 집중투자”",https://n.news.naver.com/mnews/article/366/000...,상장지수펀드(ETF)를 이달 2일 유가증권시장에 상장했다고 4일 밝혔다. ‘하나 1...
3,"대기업 그룹 채권에 집중 투자…하나운용, 국내 최초 채권형 ETF 출시",https://n.news.naver.com/mnews/article/243/000...,(A+이상)&amp;국고통안' ETF(상장지수펀드)를 2일 유가증권시장에 상장했다고...
4,키움자산운용 ETF 4종목 내달 자진 상장폐지,https://n.news.naver.com/mnews/article/001/001...,한국거래소는 신탁 원본액이 감소한 소규모 상장 상장지수펀드(ETF) 4개 종목을 운...
...,...,...,...
995,금투업계 '국감 소환' 예의주시…밸류업·금투세 쟁점,https://www.news2day.co.kr/article/20241002500029,"정무위 국감 코앞, 증인·참고인 채택기준 긴장감 증권업, 다우키움그룹 전 김익래 회..."
996,"미국증시 마감직전...반도체ETF·엔비디아·인텔 '급락', 양대 악재는?",http://www.choicenews.co.kr/news/articleView.h...,뉴욕증권거래소따르면 이 시각 뉴욕증시 반도체 관련주 흐름을 반영하는 VANECK S...
997,"한국투자신탁운용, 이머징마켓 가이드북 발간",https://www.econovill.com/news/articleView.htm...,배 사장은 &quot;ACE ETF는 현재의 글로벌 공급망 재편 속에서 인도를 중심...
998,"한국투자증권, 퇴직연금 운용사 ETF 순매수 이벤트",https://www.etoday.co.kr/news/view/2401787,상장지수펀드(ETF) 순매수 이벤트를 진행한다고 19일 밝혔다. 이번 이벤트는 개인...
999,"한투운용, 베트남·인도·인니·멕시코 투자 가이드북 발간",https://www.dnews.co.kr/uhtml/view.jsp?idxno=2...,ACE ETF 국내 유일 4개국 투자 라인업 보유 한국투자신탁운용은 오는 30일 ‘...

In [30]:
combined_df = pd.concat([combined_df, news_df], ignore_index=True)

In [34]:
combined_df = pd.concat([combined_df, web_df2], ignore_index=True)

In [36]:
combined_df.to_csv('C:/Users/KimDongyoung/Desktop/my_git/mygit/NH투자증권/네이버크롤링.csv')