In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load the uploaded CSV file to inspect its contents
file_path = 'C:/Users/KimDongyoung/Desktop/my_git/mygit/NH투자증권/NH_CONTEST_NHDATA_CUS_TP_IFO.csv'
df = pd.read_csv(file_path)

In [4]:
df_renamed = df.rename(columns={
    'bse_dt': '기준일자',
    'tck_iem_cd': '티커종목코드',
    'cus_cgr_llf_cd': '고객구성대분류코드',
    'cus_cgr_mlf_cd': '고객구성중분류코드',
    'cus_cgr_act_cnt_rt': '고객구성계좌수비율',
    'cus_cgr_ivs_rt': '고객구성투자비율'
})

In [6]:
df_renamed['고객구성대분류코드'] = df_renamed['고객구성대분류코드'].replace({
    1: '투자실력',  # Investment skills
    2: '연령대',    # Age group
    3: '자산규모'   # Asset size
})

df_renamed['고객구성중분류코드'] = df_renamed['고객구성중분류코드'].replace({
    11: '투자고수',                       # Investment expert
    12: '일반투자자',                     # General investor
    21: '0~29세',                        # 0-29 years old
    22: '30~39세',                       # 30-39 years old
    23: '40~49세',                       # 40-49 years old
    24: '50~59세',                       # 50-59 years old
    25: '60세~',                         # 60 years old and above
    31: '3천만원미만',                   # Less than 30 million won
    32: '3천만원~1억원미만',             # 30 million to less than 100 million won
    33: '1억원이상~10억원미만',           # More than 100 million to less than 1 billion won
    34: '10억원이상'                     # More than 1 billion won
})

df_renamed

             기준일자        티커종목코드 고객구성대분류코드 고객구성중분류코드  고객구성계좌수비율  고객구성투자비율
0        20240826  AAL                연령대    30~39세    37.2608   37.5675
1        20240826  AAL                연령대      60세~     4.8405   11.8565
2        20240826  AAL                연령대     0~29세    21.4259   11.5923
3        20240826  AAL                연령대    40~49세    23.9400   21.7531
4        20240816  AAL                연령대     0~29세    21.4740   11.7051
...           ...           ...       ...       ...        ...       ...
1194995  20240612  ZS                 연령대    50~59세    25.3165   23.7650
1194996  20240529  ZS                자산규모    3천만원미만    36.8421   11.7457
1194997  20240819  ZS                 연령대     0~29세    14.7059    7.2295
1194998  20240819  ZS                 연령대    40~49세    28.8235   25.3286
1194999  20240819  ZS                 연령대    50~59세    21.7647   17.5430

[1195000 rows x 6 columns]

In [19]:
# Group the data by '기준일자', '티커종목코드', and '고객구성중분류코드' (Customer Group Classification Code)
grouped_df = df_renamed.groupby(['티커종목코드', '고객구성중분류코드']).agg(
    평균고객계좌수비율=('고객구성계좌수비율', 'mean'),
    평균고객투자비율=('고객구성투자비율', 'mean')
).reset_index()

In [20]:
grouped_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21814 entries, 0 to 21813
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   티커종목코드     21814 non-null  object
 1   고객구성중분류코드  21814 non-null  object
 2   평균고객계좌수비율  21814 non-null  float64
 3   평균고객투자비율   21814 non-null  float64
dtypes: float64(2), object(2)
memory usage: 681.8+ KB

In [22]:
grouped_df[grouped_df['티커종목코드']=='AA          ']

          티커종목코드     고객구성중분류코드  평균고객계좌수비율   평균고객투자비율
0   AA                   0~29세  16.227760   9.233767
1   AA                  10억원이상   0.983323   5.746045
2   AA            1억원이상~10억원미만  19.790195  49.873048
3   AA                  30~39세  23.787049  17.304486
4   AA              3천만원~1억원미만  22.150644  24.061694
5   AA                  3천만원미만  57.231924  21.231278
6   AA                  40~49세  26.157346  29.334606
7   AA                  50~59세  24.368248  23.350663
8   AA                    60세~   9.459608  20.776495
9   AA                   일반투자자  97.615776  94.244338
10  AA                    투자고수   2.384224   5.755663

In [23]:
grouped_df.to_csv('C:/Users/KimDongyoung/Desktop/my_git/mygit/NH투자증권/NH_CONTEST_NHDATA_CUS_TP_IFO_전처리.csv', index=False)

In [25]:
df = pd.read_csv('C:/Users/KimDongyoung/Desktop/my_git/mygit/NH투자증권/NH_CONTEST_NHDATA_CUS_TP_IFO_전처리.csv')

df

             티커종목코드     고객구성중분류코드  평균고객계좌수비율   평균고객투자비율
0      AA                   0~29세  16.227760   9.233767
1      AA                  10억원이상   0.983323   5.746045
2      AA            1억원이상~10억원미만  19.790195  49.873048
3      AA                  30~39세  23.787049  17.304486
4      AA              3천만원~1억원미만  22.150644  24.061694
...             ...           ...        ...        ...
21809  ZYXI                3천만원미만  83.937998  85.637606
21810  ZYXI                40~49세  14.285700   0.714275
21811  ZYXI                50~59세  16.062002  78.993257
21812  ZYXI                 일반투자자  96.107335  99.228710
21813  ZYXI                  투자고수  14.425759   2.858312

[21814 rows x 4 columns]

In [27]:
# Remove leading and trailing spaces from '티커종목코드' column
df['티커종목코드'] = df['티커종목코드'].str.strip()

# Verify the changes
df['티커종목코드'].unique()

array(['AA', 'AAL', 'AAN', ..., 'ZVRA', 'ZYME', 'ZYXI'], dtype=object)

In [29]:
# Define a function to create QA pairs using the provided template
def generate_qa(df):
    qa_pairs = []
    for index, row in df.iterrows():
        ticker = row['티커종목코드']
        classification = row['고객구성중분류코드']
        avg_account_ratio = round(row['평균고객계좌수비율'], 2)
        avg_investment_ratio = round(row['평균고객투자비율'], 2)
        
        # Create QA pair for customer account ratio
        qa_account = {
            "question": f"What is the average customer account ratio for {classification} for ticker {ticker}?",
            "answer": f"The average customer account ratio is {avg_account_ratio}%."
        }
        qa_pairs.append(qa_account)
        
        # Create QA pair for customer investment ratio
        qa_investment = {
            "question": f"What is the average investment ratio for {classification} for ticker {ticker}?",
            "answer": f"The average investment ratio is {avg_investment_ratio}%."
        }
        qa_pairs.append(qa_investment)
    
    return qa_pairs

# Generate QA data
qa_data = generate_qa(df)

# Display first few QA pairs as an example
qa_data[:5]

[{'question': 'What is the average customer account ratio for 0~29세 for ticker AA?',
  'answer': 'The average customer account ratio is 16.23%.'},
 {'question': 'What is the average investment ratio for 0~29세 for ticker AA?',
  'answer': 'The average investment ratio is 9.23%.'},
 {'question': 'What is the average customer account ratio for 10억원이상 for ticker AA?',
  'answer': 'The average customer account ratio is 0.98%.'},
 {'question': 'What is the average investment ratio for 10억원이상 for ticker AA?',
  'answer': 'The average investment ratio is 5.75%.'},
 {'question': 'What is the average customer account ratio for 1억원이상~10억원미만 for ticker AA?',
  'answer': 'The average customer account ratio is 19.79%.'}]

In [31]:
len(qa_data)

43628

In [32]:
# Function to generate QA data for the question "What age group invested the most in ~ stocks?"
def generate_age_group_investment_qa(df):
    qa_pairs = []
    
    # Filter the dataset for age groups only
    age_group_df = df[df['고객구성중분류코드'].str.contains('세')]

    # Group by ticker and find the age group with the maximum investment ratio for each ticker
    max_investment_by_age_group = age_group_df.groupby('티커종목코드').apply(
        lambda x: x.loc[x['평균고객투자비율'].idxmax()]
    ).reset_index(drop=True)

    # Create QA pairs
    for index, row in max_investment_by_age_group.iterrows():
        ticker = row['티커종목코드'].strip()
        age_group = row['고객구성중분류코드']
        qa_pair = {
            "question": f"What age group invested the most in {ticker} stocks?",
            "answer": f"The {age_group} age group invested the most."
        }
        qa_pairs.append(qa_pair)
    
    return qa_pairs

# Generate the age group investment QA data
age_group_investment_qa = generate_age_group_investment_qa(df)

# Display first few QA pairs as an example
age_group_investment_qa[:5]

C:\Users\KimDongyoung\AppData\Local\Temp\ipykernel_16808\838978784.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  max_investment_by_age_group = age_group_df.groupby('티커종목코드').apply(

[{'question': 'What age group invested the most in AA stocks?',
  'answer': 'The 40~49세 age group invested the most.'},
 {'question': 'What age group invested the most in AAL stocks?',
  'answer': 'The 30~39세 age group invested the most.'},
 {'question': 'What age group invested the most in AAN stocks?',
  'answer': 'The 40~49세 age group invested the most.'},
 {'question': 'What age group invested the most in AAOI stocks?',
  'answer': 'The 30~39세 age group invested the most.'},
 {'question': 'What age group invested the most in AAON stocks?',
  'answer': 'The 30~39세 age group invested the most.'}]

In [39]:
len(age_group_investment_qa)

2598

In [58]:
# Function to generate QA data for the question "What age group invested the most in ~ stocks?"
def generate_perfomance_group_investment_qa(df):
    qa_pairs = []
    
    # Filter the dataset for age groups only
    age_group_df = df[df['고객구성중분류코드'].str.contains('투자')]

    # Group by ticker and find the age group with the maximum investment ratio for each ticker
    max_investment_by_age_group = age_group_df.groupby('티커종목코드').apply(
        lambda x: x.loc[x['평균고객투자비율'].idxmax()]
    ).reset_index(drop=True)

    # Create QA pairs
    for index, row in max_investment_by_age_group.iterrows():
        ticker = row['티커종목코드'].strip()
        age_group = row['고객구성중분류코드']
        qa_pair = {
            "question": f"Who invested the most in {ticker} stocks?",
            "answer": f"{age_group} invested the most."
        }
        qa_pairs.append(qa_pair)
    
    return qa_pairs

# Generate the age group investment QA data
performance_group_investment_qa = generate_perfomance_group_investment_qa(df)

# Convert the combined QA data into a dataframe with two columns: 'question' and 'answer'
qa_df_performance = pd.DataFrame(performance_group_investment_qa)

C:\Users\KimDongyoung\AppData\Local\Temp\ipykernel_16808\1201260712.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  max_investment_by_age_group = age_group_df.groupby('티커종목코드').apply(

In [59]:
qa_df_performance

                                   question                    answer
0       Who invested the most in AA stocks?  일반투자자 invested the most.
1      Who invested the most in AAL stocks?  일반투자자 invested the most.
2      Who invested the most in AAN stocks?  일반투자자 invested the most.
3     Who invested the most in AAOI stocks?  일반투자자 invested the most.
4     Who invested the most in AAON stocks?  일반투자자 invested the most.
...                                     ...                       ...
2593   Who invested the most in ZUO stocks?  일반투자자 invested the most.
2594  Who invested the most in ZURA stocks?  일반투자자 invested the most.
2595  Who invested the most in ZVRA stocks?  일반투자자 invested the most.
2596  Who invested the most in ZYME stocks?  일반투자자 invested the most.
2597  Who invested the most in ZYXI stocks?  일반투자자 invested the most.

[2598 rows x 2 columns]

In [56]:
# Function to generate QA data for the question "Stocks with what size of assets were the most invested?"
def generate_asset_size_investment_qa(df):
    qa_pairs = []
    
    # Filter the dataset for asset size groups only
    asset_size_df = df[df['고객구성중분류코드'].str.contains('억원|만원')]

    # Group by ticker and find the asset size with the maximum investment ratio for each ticker
    max_investment_by_asset_size = asset_size_df.groupby('티커종목코드').apply(
        lambda x: x.loc[x['평균고객투자비율'].idxmax()]
    ).reset_index(drop=True)

    # Create QA pairs
    for index, row in max_investment_by_asset_size.iterrows():
        ticker = row['티커종목코드'].strip()
        asset_size = row['고객구성중분류코드']
        qa_pair = {
            "question": f"{ticker} stocks with what size of assets were the most invested?",
            "answer": f"Those with {asset_size} amount of assets invested the most."
        }
        qa_pairs.append(qa_pair)
    
    return qa_pairs

# Generate the asset size investment QA data
asset_size_investment_qa = generate_asset_size_investment_qa(df)

# Display first few QA pairs as an example
asset_size_investment_qa[:20]

# Convert the combined QA data into a dataframe with two columns: 'question' and 'answer'
qa_df_asset_size = pd.DataFrame(asset_size_investment_qa)

C:\Users\KimDongyoung\AppData\Local\Temp\ipykernel_16808\4087052369.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  max_investment_by_asset_size = asset_size_df.groupby('티커종목코드').apply(

In [57]:
qa_df_asset_size

,question,answer
0,AA stocks with what size of assets were the mo...,Those with 1억원이상~10억원미만 amount of assets inves...
1,AAL stocks with what size of assets were the m...,Those with 1억원이상~10억원미만 amount of assets inves...
2,AAN stocks with what size of assets were the m...,Those with 1억원이상~10억원미만 amount of assets inves...
3,AAOI stocks with what size of assets were the ...,Those with 1억원이상~10억원미만 amount of assets inves...
4,AAON stocks with what size of assets were the ...,Those with 1억원이상~10억원미만 amount of assets inves...
...,...,...
2593,ZUO stocks with what size of assets were the m...,Those with 3천만원미만 amount of assets invested th...
2594,ZURA stocks with what size of assets were the ...,Those with 1억원이상~10억원미만 amount of assets inves...
2595,ZVRA stocks with what size of assets were the ...,Those with 3천만원~1억원미만 amount of assets investe...
2596,ZYME stocks with what size of assets were the ...,Those with 3천만원미만 amount of assets invested th...
2597,ZYXI stocks with what size of assets were the ...,Those with 3천만원미만 amount of assets invested th...

In [54]:
# Function to generate combined QA pairs
def generate_combined_qa(df):
    qa_pairs = []
    
    # Get unique tickers
    tickers = df['티커종목코드'].unique()
    
    for ticker in tickers:
        # Filter data for the current ticker
        ticker_df = df[df['티커종목코드'] == ticker]
        
        # Filter for age groups (assuming age groups contain '세')
        age_group_df = ticker_df[ticker_df['고객구성중분류코드'].str.contains('세')]
        if not age_group_df.empty:
            # Find the age group with the highest investment ratio
            top_age_group = age_group_df.loc[age_group_df['평균고객투자비율'].idxmax()]['고객구성중분류코드']
        else:
            top_age_group = "정보 없음"
        
        # Filter for asset sizes (assuming asset sizes contain '만원' or '억원')
        asset_size_df = ticker_df[ticker_df['고객구성중분류코드'].str.contains('만원|억원')]
        if not asset_size_df.empty:
            # Find the asset size with the highest investment ratio
            top_asset_size = asset_size_df.loc[asset_size_df['평균고객투자비율'].idxmax()]['고객구성중분류코드']
        else:
            top_asset_size = "정보 없음"
        
        # Create the QA pair
        qa_pair = {
            "question": f"Please tell me about the customer group that purchased {ticker} stocks.",
            "answer": f"{ticker} stocks are most held by customers of the {top_age_group} age group, and customers with {top_asset_size} asset size are the largest."
        }
        qa_pairs.append(qa_pair)
    
    return qa_pairs

# Generate the combined QA data
combined_qa_data = generate_combined_qa(df)

# Display first few QA pairs as an example
combined_qa_data[:5]

# Convert the combined QA data into a dataframe with two columns: 'question' and 'answer'
qa_df = pd.DataFrame(combined_qa_data)

In [55]:
qa_df

,question,answer
0,Please tell me about the customer group that p...,AA stocks are most held by customers of the 40...
1,Please tell me about the customer group that p...,AAL stocks are most held by customers of the 3...
2,Please tell me about the customer group that p...,AAN stocks are most held by customers of the 4...
3,Please tell me about the customer group that p...,AAOI stocks are most held by customers of the ...
4,Please tell me about the customer group that p...,AAON stocks are most held by customers of the ...
...,...,...
2593,Please tell me about the customer group that p...,ZUO stocks are most held by customers of the 5...
2594,Please tell me about the customer group that p...,ZURA stocks are most held by customers of the ...
2595,Please tell me about the customer group that p...,ZVRA stocks are most held by customers of the ...
2596,Please tell me about the customer group that p...,ZYME stocks are most held by customers of the ...
2597,Please tell me about the customer group that p...,ZYXI stocks are most held by customers of the ...

하나의 리스트로 결합

In [40]:
combined_list = [combined_qa_data, asset_size_investment_qa, age_group_investment_qa, qa_data]

In [41]:
combined_list

[[{'question': 'Please tell me about the customer group that purchased AA stocks.',
   'answer': 'AA stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AAL stocks.',
   'answer': 'AAL stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AAN stocks.',
   'answer': 'AAN stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AAOI stocks.',
   'answer': 'AAOI stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AAON stocks.',
   'answer': 'AAON stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AAP stocks.',
   'answer': 'AAP stocks are most held by customers of the 50~59세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AAPB stocks.',
   'answer': 'AAPB stocks are most held by customers of the 30~39세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AAPL stocks.',
   'answer': 'AAPL stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AAPU stocks.',
   'answer': 'AAPU stocks are most held by customers of the 0~29세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AAT stocks.',
   'answer': 'AAT stocks are most held by customers of the 50~59세 age group, and customers with 10억원이상 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ABBV stocks.',
   'answer': 'ABBV stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ABCB stocks.',
   'answer': 'ABCB stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ABCL stocks.',
   'answer': 'ABCL stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ABG stocks.',
   'answer': 'ABG stocks are most held by customers of the 0~29세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ABM stocks.',
   'answer': 'ABM stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ABNB stocks.',
   'answer': 'ABNB stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ABOS stocks.',
   'answer': 'ABOS stocks are most held by customers of the 40~49세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ABR stocks.',
   'answer': 'ABR stocks are most held by customers of the 50~59세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ABSI stocks.',
   'answer': 'ABSI stocks are most held by customers of the 50~59세 age group, and customers with 10억원이상 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ABT stocks.',
   'answer': 'ABT stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ABUS stocks.',
   'answer': 'ABUS stocks are most held by customers of the 30~39세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AC stocks.',
   'answer': 'AC stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACAD stocks.',
   'answer': 'ACAD stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACCD stocks.',
   'answer': 'ACCD stocks are most held by customers of the 40~49세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACCO stocks.',
   'answer': 'ACCO stocks are most held by customers of the 0~29세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACDC stocks.',
   'answer': 'ACDC stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACGL stocks.',
   'answer': 'ACGL stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACHC stocks.',
   'answer': 'ACHC stocks are most held by customers of the 0~29세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACHR stocks.',
   'answer': 'ACHR stocks are most held by customers of the 50~59세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACHV stocks.',
   'answer': 'ACHV stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACI stocks.',
   'answer': 'ACI stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACIU stocks.',
   'answer': 'ACIU stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACIW stocks.',
   'answer': 'ACIW stocks are most held by customers of the 40~49세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACLS stocks.',
   'answer': 'ACLS stocks are most held by customers of the 50~59세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACLX stocks.',
   'answer': 'ACLX stocks are most held by customers of the 50~59세 age group, and customers with 10억원이상 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACM stocks.',
   'answer': 'ACM stocks are most held by customers of the 0~29세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACMR stocks.',
   'answer': 'ACMR stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACN stocks.',
   'answer': 'ACN stocks are most held by customers of the 50~59세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACRE stocks.',
   'answer': 'ACRE stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACRS stocks.',
   'answer': 'ACRS stocks are most held by customers of the 40~49세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACRV stocks.',
   'answer': 'ACRV stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACT stocks.',
   'answer': 'ACT stocks are most held by customers of the 50~59세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACTG stocks.',
   'answer': 'ACTG stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ACVA stocks.',
   'answer': 'ACVA stocks are most held by customers of the 50~59세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADBE stocks.',
   'answer': 'ADBE stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADC stocks.',
   'answer': 'ADC stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADEA stocks.',
   'answer': 'ADEA stocks are most held by customers of the 50~59세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADI stocks.',
   'answer': 'ADI stocks are most held by customers of the 60세~ age group, and customers with 10억원이상 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADM stocks.',
   'answer': 'ADM stocks are most held by customers of the 30~39세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADMA stocks.',
   'answer': 'ADMA stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADNT stocks.',
   'answer': 'ADNT stocks are most held by customers of the 50~59세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADP stocks.',
   'answer': 'ADP stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADPT stocks.',
   'answer': 'ADPT stocks are most held by customers of the 50~59세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADSK stocks.',
   'answer': 'ADSK stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADT stocks.',
   'answer': 'ADT stocks are most held by customers of the 30~39세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADTN stocks.',
   'answer': 'ADTN stocks are most held by customers of the 50~59세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADUS stocks.',
   'answer': 'ADUS stocks are most held by customers of the 0~29세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADV stocks.',
   'answer': 'ADV stocks are most held by customers of the 50~59세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased ADVM stocks.',
   'answer': 'ADVM stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AEE stocks.',
   'answer': 'AEE stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AEHR stocks.',
   'answer': 'AEHR stocks are most held by customers of the 40~49세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AEIS stocks.',
   'answer': 'AEIS stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AEM stocks.',
   'answer': 'AEM stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AEO stocks.',
   'answer': 'AEO stocks are most held by customers of the 40~49세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AEP stocks.',
   'answer': 'AEP stocks are most held by customers of the 50~59세 age group, and customers with 10억원이상 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AER stocks.',
   'answer': 'AER stocks are most held by customers of the 40~49세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AES stocks.',
   'answer': 'AES stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AESI stocks.',
   'answer': 'AESI stocks are most held by customers of the 0~29세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AEVA stocks.',
   'answer': 'AEVA stocks are most held by customers of the 50~59세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AEYE stocks.',
   'answer': 'AEYE stocks are most held by customers of the 50~59세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AFCG stocks.',
   'answer': 'AFCG stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AFG stocks.',
   'answer': 'AFG stocks are most held by customers of the 30~39세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AFL stocks.',
   'answer': 'AFL stocks are most held by customers of the 50~59세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AFRM stocks.',
   'answer': 'AFRM stocks are most held by customers of the 60세~ age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AG stocks.',
   'answer': 'AG stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AGCO stocks.',
   'answer': 'AGCO stocks are most held by customers of the 50~59세 age group, and customers with 10억원이상 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AGEN stocks.',
   'answer': 'AGEN stocks are most held by customers of the 40~49세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AGI stocks.',
   'answer': 'AGI stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AGIO stocks.',
   'answer': 'AGIO stocks are most held by customers of the 0~29세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AGL stocks.',
   'answer': 'AGL stocks are most held by customers of the 0~29세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AGM stocks.',
   'answer': 'AGM stocks are most held by customers of the 30~39세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AGNC stocks.',
   'answer': 'AGNC stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AGR stocks.',
   'answer': 'AGR stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AGS stocks.',
   'answer': 'AGS stocks are most held by customers of the 50~59세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AGX stocks.',
   'answer': 'AGX stocks are most held by customers of the 30~39세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AGYS stocks.',
   'answer': 'AGYS stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AHCO stocks.',
   'answer': 'AHCO stocks are most held by customers of the 30~39세 age group, and customers with 3천만원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AHH stocks.',
   'answer': 'AHH stocks are most held by customers of the 30~39세 age group, and customers with 3천만원~1억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AI stocks.',
   'answer': 'AI stocks are most held by customers of the 40~49세 age group, and customers with 1억원이상~10억원미만 asset size are the largest.'},
  {'question': 'Please tell me about the customer group that purchased AIA stocks.',

In [48]:
import random

random.shuffle(combined_list)

In [49]:
combined_list

[[{'question': 'What is the average customer account ratio for 0~29세 for ticker AA?',
   'answer': 'The average customer account ratio is 16.23%.'},
  {'question': 'What is the average investment ratio for 0~29세 for ticker AA?',
   'answer': 'The average investment ratio is 9.23%.'},
  {'question': 'What is the average customer account ratio for 10억원이상 for ticker AA?',
   'answer': 'The average customer account ratio is 0.98%.'},
  {'question': 'What is the average investment ratio for 10억원이상 for ticker AA?',
   'answer': 'The average investment ratio is 5.75%.'},
  {'question': 'What is the average customer account ratio for 1억원이상~10억원미만 for ticker AA?',
   'answer': 'The average customer account ratio is 19.79%.'},
  {'question': 'What is the average investment ratio for 1억원이상~10억원미만 for ticker AA?',
   'answer': 'The average investment ratio is 49.87%.'},
  {'question': 'What is the average customer account ratio for 30~39세 for ticker AA?',
   'answer': 'The average customer account ratio is 23.79%.'},
  {'question': 'What is the average investment ratio for 30~39세 for ticker AA?',
   'answer': 'The average investment ratio is 17.3%.'},
  {'question': 'What is the average customer account ratio for 3천만원~1억원미만 for ticker AA?',
   'answer': 'The average customer account ratio is 22.15%.'},
  {'question': 'What is the average investment ratio for 3천만원~1억원미만 for ticker AA?',
   'answer': 'The average investment ratio is 24.06%.'},
  {'question': 'What is the average customer account ratio for 3천만원미만 for ticker AA?',
   'answer': 'The average customer account ratio is 57.23%.'},
  {'question': 'What is the average investment ratio for 3천만원미만 for ticker AA?',
   'answer': 'The average investment ratio is 21.23%.'},
  {'question': 'What is the average customer account ratio for 40~49세 for ticker AA?',
   'answer': 'The average customer account ratio is 26.16%.'},
  {'question': 'What is the average investment ratio for 40~49세 for ticker AA?',
   'answer': 'The average investment ratio is 29.33%.'},
  {'question': 'What is the average customer account ratio for 50~59세 for ticker AA?',
   'answer': 'The average customer account ratio is 24.37%.'},
  {'question': 'What is the average investment ratio for 50~59세 for ticker AA?',
   'answer': 'The average investment ratio is 23.35%.'},
  {'question': 'What is the average customer account ratio for 60세~ for ticker AA?',
   'answer': 'The average customer account ratio is 9.46%.'},
  {'question': 'What is the average investment ratio for 60세~ for ticker AA?',
   'answer': 'The average investment ratio is 20.78%.'},
  {'question': 'What is the average customer account ratio for 일반투자자 for ticker AA?',
   'answer': 'The average customer account ratio is 97.62%.'},
  {'question': 'What is the average investment ratio for 일반투자자 for ticker AA?',
   'answer': 'The average investment ratio is 94.24%.'},
  {'question': 'What is the average customer account ratio for 투자고수 for ticker AA?',
   'answer': 'The average customer account ratio is 2.38%.'},
  {'question': 'What is the average investment ratio for 투자고수 for ticker AA?',
   'answer': 'The average investment ratio is 5.76%.'},
  {'question': 'What is the average customer account ratio for 0~29세 for ticker AAL?',
   'answer': 'The average customer account ratio is 21.7%.'},
  {'question': 'What is the average investment ratio for 0~29세 for ticker AAL?',
   'answer': 'The average investment ratio is 12.08%.'},
  {'question': 'What is the average customer account ratio for 10억원이상 for ticker AAL?',
   'answer': 'The average customer account ratio is 0.24%.'},
  {'question': 'What is the average investment ratio for 10억원이상 for ticker AAL?',
   'answer': 'The average investment ratio is 9.58%.'},
  {'question': 'What is the average customer account ratio for 1억원이상~10억원미만 for ticker AAL?',
   'answer': 'The average customer account ratio is 9.01%.'},
  {'question': 'What is the average investment ratio for 1억원이상~10억원미만 for ticker AAL?',
   'answer': 'The average investment ratio is 35.12%.'},
  {'question': 'What is the average customer account ratio for 30~39세 for ticker AAL?',
   'answer': 'The average customer account ratio is 37.43%.'},
  {'question': 'What is the average investment ratio for 30~39세 for ticker AAL?',
   'answer': 'The average investment ratio is 39.25%.'},
  {'question': 'What is the average customer account ratio for 3천만원~1억원미만 for ticker AAL?',
   'answer': 'The average customer account ratio is 19.63%.'},
  {'question': 'What is the average investment ratio for 3천만원~1억원미만 for ticker AAL?',
   'answer': 'The average investment ratio is 28.24%.'},
  {'question': 'What is the average customer account ratio for 3천만원미만 for ticker AAL?',
   'answer': 'The average customer account ratio is 71.08%.'},
  {'question': 'What is the average investment ratio for 3천만원미만 for ticker AAL?',
   'answer': 'The average investment ratio is 27.06%.'},
  {'question': 'What is the average customer account ratio for 40~49세 for ticker AAL?',
   'answer': 'The average customer account ratio is 23.69%.'},
  {'question': 'What is the average investment ratio for 40~49세 for ticker AAL?',
   'answer': 'The average investment ratio is 19.11%.'},
  {'question': 'What is the average customer account ratio for 50~59세 for ticker AAL?',
   'answer': 'The average customer account ratio is 12.6%.'},
  {'question': 'What is the average investment ratio for 50~59세 for ticker AAL?',
   'answer': 'The average investment ratio is 17.72%.'},
  {'question': 'What is the average customer account ratio for 60세~ for ticker AAL?',
   'answer': 'The average customer account ratio is 4.58%.'},
  {'question': 'What is the average investment ratio for 60세~ for ticker AAL?',
   'answer': 'The average investment ratio is 11.85%.'},
  {'question': 'What is the average customer account ratio for 일반투자자 for ticker AAL?',
   'answer': 'The average customer account ratio is 98.39%.'},
  {'question': 'What is the average investment ratio for 일반투자자 for ticker AAL?',
   'answer': 'The average investment ratio is 97.91%.'},
  {'question': 'What is the average customer account ratio for 투자고수 for ticker AAL?',
   'answer': 'The average customer account ratio is 1.61%.'},
  {'question': 'What is the average investment ratio for 투자고수 for ticker AAL?',
   'answer': 'The average investment ratio is 2.09%.'},
  {'question': 'What is the average customer account ratio for 0~29세 for ticker AAN?',
   'answer': 'The average customer account ratio is 8.33%.'},
  {'question': 'What is the average investment ratio for 0~29세 for ticker AAN?',
   'answer': 'The average investment ratio is 1.08%.'},
  {'question': 'What is the average customer account ratio for 1억원이상~10억원미만 for ticker AAN?',
   'answer': 'The average customer account ratio is 17.14%.'},
  {'question': 'What is the average investment ratio for 1억원이상~10억원미만 for ticker AAN?',
   'answer': 'The average investment ratio is 68.81%.'},
  {'question': 'What is the average customer account ratio for 30~39세 for ticker AAN?',
   'answer': 'The average customer account ratio is 59.74%.'},
  {'question': 'What is the average investment ratio for 30~39세 for ticker AAN?',
   'answer': 'The average investment ratio is 12.69%.'},
  {'question': 'What is the average customer account ratio for 3천만원~1억원미만 for ticker AAN?',
   'answer': 'The average customer account ratio is 9.82%.'},
  {'question': 'What is the average investment ratio for 3천만원~1억원미만 for ticker AAN?',
   'answer': 'The average investment ratio is 12.46%.'},
  {'question': 'What is the average customer account ratio for 3천만원미만 for ticker AAN?',
   'answer': 'The average customer account ratio is 73.04%.'},
  {'question': 'What is the average investment ratio for 3천만원미만 for ticker AAN?',
   'answer': 'The average investment ratio is 18.72%.'},
  {'question': 'What is the average customer account ratio for 40~49세 for ticker AAN?',
   'answer': 'The average customer account ratio is 37.19%.'},
  {'question': 'What is the average investment ratio for 40~49세 for ticker AAN?',
   'answer': 'The average investment ratio is 85.37%.'},
  {'question': 'What is the average customer account ratio for 50~59세 for ticker AAN?',
   'answer': 'The average customer account ratio is 8.82%.'},
  {'question': 'What is the average investment ratio for 50~59세 for ticker AAN?',
   'answer': 'The average investment ratio is 5.76%.'},
  {'question': 'What is the average customer account ratio for 일반투자자 for ticker AAN?',
   'answer': 'The average customer account ratio is 99.55%.'},
  {'question': 'What is the average investment ratio for 일반투자자 for ticker AAN?',
   'answer': 'The average investment ratio is 99.99%.'},
  {'question': 'What is the average customer account ratio for 투자고수 for ticker AAN?',
   'answer': 'The average customer account ratio is 7.14%.'},
  {'question': 'What is the average investment ratio for 투자고수 for ticker AAN?',
   'answer': 'The average investment ratio is 0.18%.'},
  {'question': 'What is the average customer account ratio for 0~29세 for ticker AAOI?',
   'answer': 'The average customer account ratio is 31.39%.'},
  {'question': 'What is the average investment ratio for 0~29세 for ticker AAOI?',
   'answer': 'The average investment ratio is 2.62%.'},
  {'question': 'What is the average customer account ratio for 1억원이상~10억원미만 for ticker AAOI?',
   'answer': 'The average customer account ratio is 17.18%.'},
  {'question': 'What is the average investment ratio for 1억원이상~10억원미만 for ticker AAOI?',
   'answer': 'The average investment ratio is 88.3%.'},
  {'question': 'What is the average customer account ratio for 30~39세 for ticker AAOI?',
   'answer': 'The average customer account ratio is 37.48%.'},
  {'question': 'What is the average investment ratio for 30~39세 for ticker AAOI?',
   'answer': 'The average investment ratio is 56.7%.'},
  {'question': 'What is the average customer account ratio for 3천만원~1억원미만 for ticker AAOI?',
   'answer': 'The average customer account ratio is 16.13%.'},
  {'question': 'What is the average investment ratio for 3천만원~1억원미만 for ticker AAOI?',
   'answer': 'The average investment ratio is 4.42%.'},
  {'question': 'What is the average customer account ratio for 3천만원미만 for ticker AAOI?',
   'answer': 'The average customer account ratio is 66.69%.'},
  {'question': 'What is the average investment ratio for 3천만원미만 for ticker AAOI?',
   'answer': 'The average investment ratio is 7.28%.'},
  {'question': 'What is the average customer account ratio for 40~49세 for ticker AAOI?',
   'answer': 'The average customer account ratio is 7.86%.'},
  {'question': 'What is the average investment ratio for 40~49세 for ticker AAOI?',
   'answer': 'The average investment ratio is 0.49%.'},
  {'question': 'What is the average customer account ratio for 50~59세 for ticker AAOI?',
   'answer': 'The average customer account ratio is 18.05%.'},
  {'question': 'What is the average investment ratio for 50~59세 for ticker AAOI?',
   'answer': 'The average investment ratio is 39.63%.'},
  {'question': 'What is the average customer account ratio for 60세~ for ticker AAOI?',
   'answer': 'The average customer account ratio is 5.22%.'},
  {'question': 'What is the average investment ratio for 60세~ for ticker AAOI?',
   'answer': 'The average investment ratio is 0.56%.'},
  {'question': 'What is the average customer account ratio for 일반투자자 for ticker AAOI?',
   'answer': 'The average customer account ratio is 95.51%.'},
  {'question': 'What is the average investment ratio for 일반투자자 for ticker AAOI?',
   'answer': 'The average investment ratio is 98.03%.'},
  {'question': 'What is the average customer account ratio for 투자고수 for ticker AAOI?',
   'answer': 'The average customer account ratio is 6.15%.'},
  {'question': 'What is the average investment ratio for 투자고수 for ticker AAOI?',
   'answer': 'The average investment ratio is 2.69%.'},
  {'question': 'What is the average customer account ratio for 1억원이상~10억원미만 for ticker AAON?',
   'answer': 'The average customer account ratio is 81.69%.'},
  {'question': 'What is the average investment ratio for 1억원이상~10억원미만 for ticker AAON?',
   'answer': 'The average investment ratio is 70.99%.'},
  {'question': 'What is the average customer account ratio for 30~39세 for ticker AAON?',
   'answer': 'The average customer account ratio is 35.72%.'},
  {'question': 'What is the average investment ratio for 30~39세 for ticker AAON?',
   'answer': 'The average investment ratio is 67.33%.'},
  {'question': 'What is the average customer account ratio for 3천만원~1억원미만 for ticker AAON?',
   'answer': 'The average customer account ratio is 34.65%.'},
  {'question': 'What is the average investment ratio for 3천만원~1억원미만 for ticker AAON?',
   'answer': 'The average investment ratio is 68.93%.'},
  {'question': 'What is the average customer account ratio for 3천만원미만 for ticker AAON?',
   'answer': 'The average customer account ratio is 38.08%.'},
  {'question': 'What is the average investment ratio for 3천만원미만 for ticker AAON?',
   'answer': 'The average investment ratio is 39.85%.'},
  {'question': 'What is the average customer account ratio for 40~49세 for ticker AAON?',
   'answer': 'The average customer account ratio is 40.85%.'},
  {'question': 'What is the average investment ratio for 40~49세 for ticker AAON?',
   'answer': 'The average investment ratio is 21.62%.'},
  {'question': 'What is the average customer account ratio for 50~59세 for ticker AAON?',
   'answer': 'The average customer account ratio is 46.11%.'},
  {'question': 'What is the average investment ratio for 50~59세 for ticker AAON?',
   'answer': 'The average investment ratio is 53.79%.'},
  {'question': 'What is the average customer account ratio for 일반투자자 for ticker AAON?',
   'answer': 'The average customer account ratio is 100.0%.'},
  {'question': 'What is the average investment ratio for 일반투자자 for ticker AAON?',
   'answer': 'The average investment ratio is 100.0%.'},
  {'question': 'What is the average customer account ratio for 0~29세 for ticker AAP?',
   'answer': 'The average customer account ratio is 8.71%.'},
  {'question': 'What is the average investment ratio for 0~29세 for ticker AAP?',
   'answer': 'The average investment ratio is 7.26%.'},
  {'question': 'What is the average customer account ratio for 10억원이상 for ticker AAP?',
   'answer': 'The average customer account ratio is 11.38%.'},
  {'question': 'What is the average investment ratio for 10억원이상 for ticker AAP?',
   'answer': 'The average investment ratio is 1.62%.'},
  {'question': 'What is the average customer account ratio for 1억원이상~10억원미만 for ticker AAP?',
   'answer': 'The average customer account ratio is 17.78%.'},
  {'question': 'What is the average investment ratio for 1억원이상~10억원미만 for ticker AAP?',
   'answer': 'The average investment ratio is 4.95%.'},
  {'question': 'What is the average customer account ratio for 30~39세 for ticker AAP?',
   'answer': 'The average customer account ratio is 11.11%.'},
  {'question': 'What is the average investment ratio for 30~39세 for ticker AAP?',
   'answer': 'The average investment ratio is 9.65%.'},
  {'question': 'What is the average customer account ratio for 3천만원~1억원미만 for ticker AAP?',
   'answer': 'The average customer account ratio is 23.07%.'},
  {'question': 'What is the average investment ratio for 3천만원~1억원미만 for ticker AAP?',
   'answer': 'The average investment ratio is 48.52%.'},
  {'question': 'What is the average customer account ratio for 3천만원미만 for ticker AAP?',
   'answer': 'The average customer account ratio is 47.78%.'},
  {'question': 'What is the average investment ratio for 3천만원미만 for ticker AAP?',
   'answer': 'The average investment ratio is 44.91%.'},
  {'question': 'What is the average customer account ratio for 40~49세 for ticker AAP?',
   'answer': 'The average customer account ratio is 29.33%.'},
  {'question': 'What is the average investment ratio for 40~49세 for ticker AAP?',
   'answer': 'The average investment ratio is 12.97%.'},
  {'question': 'What is the average customer account ratio for 50~59세 for ticker AAP?',
   'answer': 'The average customer account ratio is 57.03%.'},
  {'question': 'What is the average investment ratio for 50~59세 for ticker AAP?',
   'answer': 'The average investment ratio is 83.99%.'},
  {'question': 'What is the average customer account ratio for 60세~ for ticker AAP?',
   'answer': 'The average customer account ratio is 12.13%.'},
  {'question': 'What is the average investment ratio for 60세~ for ticker AAP?',
   'answer': 'The average investment ratio is 1.74%.'},
  {'question': 'What is the average customer account ratio for 일반투자자 for ticker AAP?',
   'answer': 'The average customer account ratio is 99.29%.'},
  {'question': 'What is the average investment ratio for 일반투자자 for ticker AAP?',
   'answer': 'The average investment ratio is 97.41%.'},
  {'question': 'What is the average customer account ratio for 투자고수 for ticker AAP?',
   'answer': 'The average customer account ratio is 11.11%.'},
  {'question': 'What is the average investment ratio for 투자고수 for ticker AAP?',
   'answer': 'The average investment ratio is 40.76%.'},
  {'question': 'What is the average customer account ratio for 0~29세 for ticker AAPB?',
   'answer': 'The average customer account ratio is 26.64%.'},
  {'question': 'What is the average investment ratio for 0~29세 for ticker AAPB?',
   'answer': 'The average investment ratio is 18.37%.'},
  {'question': 'What is the average customer account ratio for 10억원이상 for ticker AAPB?',
   'answer': 'The average customer account ratio is 1.31%.'},
  {'question': 'What is the average investment ratio for 10억원이상 for ticker AAPB?',
   'answer': 'The average investment ratio is 5.55%.'},
  {'question': 'What is the average customer account ratio for 1억원이상~10억원미만 for ticker AAPB?',
   'answer': 'The average customer account ratio is 13.67%.'},
  {'question': 'What is the average investment ratio for 1억원이상~10억원미만 for ticker AAPB?',
   'answer': 'The average investment ratio is 27.03%.'},
  {'question': 'What is the average customer account ratio for 30~39세 for ticker AAPB?',
   'answer': 'The average customer account ratio is 36.45%.'},
  {'question': 'What is the average investment ratio for 30~39세 for ticker AAPB?',
   'answer': 'The average investment ratio is 43.01%.'},
  {'question': 'What is the average customer account ratio for 3천만원~1억원미만 for ticker AAPB?',
   'answer': 'The average customer account ratio is 26.41%.'},
  {'question': 'What is the average investment ratio for 3천만원~1억원미만 for ticker AAPB?',
   'answer': 'The average investment ratio is 35.83%.'},
  {'question': 'What is the average customer account ratio for 3천만원미만 for ticker AAPB?',
   'answer': 'The average customer account ratio is 58.61%.'},
  {'question': 'What is the average investment ratio for 3천만원미만 for ticker AAPB?',
   'answer': 'The average investment ratio is 31.59%.'},
  {'question': 'What is the average customer account ratio for 40~49세 for ticker AAPB?',
   'answer': 'The average customer account ratio is 22.47%.'},
  {'question': 'What is the average investment ratio for 40~49세 for ticker AAPB?',
   'answer': 'The average investment ratio is 26.25%.'},
  {'question': 'What is the average customer account ratio for 50~59세 for ticker AAPB?',
   'answer': 'The average customer account ratio is 10.4%.'},
  {'question': 'What is the average investment ratio for 50~59세 for ticker AAPB?',
   'answer': 'The average investment ratio is 10.99%.'},
  {'question': 'What is the average customer account ratio for 60세~ for ticker AAPB?',
   'answer': 'The average customer account ratio is 4.04%.'},
  {'question': 'What is the average investment ratio for 60세~ for ticker AAPB?',
   'answer': 'The average investment ratio is 1.39%.'},
  {'question': 'What is the average customer account ratio for 일반투자자 for ticker AAPB?',
   'answer': 'The average customer account ratio is 93.0%.'},

In [50]:
# combined_list를 DataFrame으로 변환
final_df = pd.DataFrame(combined_list)

In [51]:
final_df

,0,1,2,3,4,5,6,7,8,9,...,43618,43619,43620,43621,43622,43623,43624,43625,43626,43627
0,{'question': 'What is the average customer acc...,{'question': 'What is the average investment r...,{'question': 'What is the average customer acc...,{'question': 'What is the average investment r...,{'question': 'What is the average customer acc...,{'question': 'What is the average investment r...,{'question': 'What is the average customer acc...,{'question': 'What is the average investment r...,{'question': 'What is the average customer acc...,{'question': 'What is the average investment r...,...,{'question': 'What is the average customer acc...,{'question': 'What is the average investment r...,{'question': 'What is the average customer acc...,{'question': 'What is the average investment r...,{'question': 'What is the average customer acc...,{'question': 'What is the average investment r...,{'question': 'What is the average customer acc...,{'question': 'What is the average investment r...,{'question': 'What is the average customer acc...,{'question': 'What is the average investment r...
1,{'question': 'AA stocks with what size of asse...,{'question': 'AAL stocks with what size of ass...,{'question': 'AAN stocks with what size of ass...,{'question': 'AAOI stocks with what size of as...,{'question': 'AAON stocks with what size of as...,{'question': 'AAP stocks with what size of ass...,{'question': 'AAPB stocks with what size of as...,{'question': 'AAPL stocks with what size of as...,{'question': 'AAPU stocks with what size of as...,{'question': 'AAT stocks with what size of ass...,...,None,None,None,None,None,None,None,None,None,None
2,{'question': 'Please tell me about the custome...,{'question': 'Please tell me about the custome...,{'question': 'Please tell me about the custome...,{'question': 'Please tell me about the custome...,{'question': 'Please tell me about the custome...,{'question': 'Please tell me about the custome...,{'question': 'Please tell me about the custome...,{'question': 'Please tell me about the custome...,{'question': 'Please tell me about the custome...,{'question': 'Please tell me about the custome...,...,None,None,None,None,None,None,None,None,None,None
3,{'question': 'What age group invested the most...,{'question': 'What age group invested the most...,{'question': 'What age group invested the most...,{'question': 'What age group invested the most...,{'question': 'What age group invested the most...,{'question': 'What age group invested the most...,{'question': 'What age group invested the most...,{'question': 'What age group invested the most...,{'question': 'What age group invested the most...,{'question': 'What age group invested the most...,...,None,None,None,None,None,None,None,None,None,None